api_platform:
  title: Barbers API
  version: 1.0.0

  show_webby: false

  defaults:
    pagination_enabled: true
    pagination_item_per_page: 3
    pagination_client_enabled: true
    pagination_client_items_per_page: true

    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    extra_properties:
      standard_put: true

  collection:
    pagination:
      enabled_parameter_name: "pagination"
      items_per_page_parameter_name: "perPage"
      page_parameter_name: "page"
      partial_parameter_name: "partial"

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header

  patch_formats:
    json: ["application/json"]

  formats:
    json: ["application/json"]
    jsonld: ["application/ld+json"]
    html: ["text/html"]
    jsonapi: ["application/vnd.api+json"]
