api_platform:
    title: Hello API Platform
    version: 1.0.0

    show_webby: false

    defaults:
        pagination_enables: true
        pagination_item_per_page: 3
        pagination_partial: true
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        pagination_client_partial: true

        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true

    collection:
        pagination:
            enabled_parameter_name: 'pagination'
            items_per_page_parameter_name: 'itemsPerPage'
            page_parameter_name: 'page'
            partial_parameter_name: 'partial'

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

    formats:
        json:
            mime_types: [ 'application/json' ]
        jsonld:
            mime_types: [ 'application/ld+json' ]
        html:
            mime_types: [ 'text/html' ]