nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(MANAGER_URL)%', '%env(WEBSITE_URL)%', '%env(ADMIN_URL)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
