name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest main branch
        run: git fetch origin main:refs/remotes/origin/main
      
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet HEAD refs/remotes/origin/main; then
            echo "No changes detected since last merge with origin/main."
            echo "HAS_CHANGES=false" >> $GITHUB_ENV
          else
            echo "Changes detected since last merge with origin/main."
            echo "HAS_CHANGES=true" >> $GITHUB_ENV
          fi
      
      - name: Deploy to Heroku
        if: env.HAS_CHANGES == 'true'
        uses: CDNievas/heroku-action@v1.0
        with:
          heroku_email: "karmimchakib@gmail.com"
          heroku_api_key: "${{secrets.HEROKU_API_KEY}}"
          heroku_app_name: "barbers-esgi"
